const OwnicNFTMarketplace = artifacts.require("OwnicNFTMarketplace");
const NFTCategoryController = artifacts.require("NFTCategoryController");
const EternalStorage = artifacts.require("EternalStorage");
const NFTCategoriesLibrary = artifacts.require("NFTCategoriesLibrary");
const NebulaToken = artifacts.require("NebulaToken");
const NebulaDynamicCollection = artifacts.require("NebulaDynamicCollection");
const OwnicPlayerOpener = artifacts.require("OwnicPlayerOpener");


async function getByte32(string) {
    return web3.utils.keccak256(string);
}

module.exports = async function (deployer, network, accounts) {

    let controller = await NFTCategoryController.deployed();

    let classIdA = 0;
    let classIdB = 1;
    let classIdC = 2;
    let classIdD = 3;
    let classIdE = 4;
    let classIdF = 5;
    let classIdG = 6;


    let defender = await getByte32("Defender");
    let goalkeeper = await getByte32("Goalkeeper");
    let midfielder = await getByte32("Midfielder");
    let attacker = await getByte32("Attacker");
    
    let curCategoryId = 1000; 

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jan Oblak 2021"), classIdA, goalkeeper, 91, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Gianluigi Donnarumma 2021"), classIdA, goalkeeper, 89, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Virgil van Dijk 2021"), classIdA, defender, 89, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Sergio Ramos 2021"), classIdA, defender, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Rúben Dias 2021"), classIdA, defender, 87, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Marquinhos 2021"), classIdA, defender, 87, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Trent Alexander-Arnold 2021"), classIdA, defender, 87, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Andrew Robertson 2021"), classIdA, defender, 87, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Kevin De Bruyne 2021"), classIdA, midfielder, 91, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Joshua Kimmich 2021"), classIdA, midfielder, 89, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Casemiro 2021"), classIdA, midfielder, 89, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Bruno Fernandes 2021"), classIdA, midfielder, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Frenkie de Jong 2021"), classIdA, midfielder, 87, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Lionel Messi 2021"), classIdA, attacker, 93, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Robert Lewandowski 2021"), classIdA, attacker, 92, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Kylian Mbappé 2021"), classIdA, attacker, 91, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Cristiano Ronaldo 2021"), classIdA, attacker, 91, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Neymar Jr 2021"), classIdA, attacker, 91, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Harry Kane 2021"), classIdA, attacker, 90, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Alisson 2021"), classIdB, goalkeeper, 89, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Ederson 2021"), classIdB, goalkeeper, 89, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Thibaut Courtois 2021"), classIdB, goalkeeper, 89, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Keylor Navas 2021"), classIdB, goalkeeper, 89, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Milan Škriniar 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Aymeric Laporte 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("João Cancelo 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Fabinho 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Raphaël Varane 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Kalidou Koulibaly 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jordi Alba 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jordi Alba 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Mats Hummels 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Giorgio Chiellini 2021"), classIdB, defender, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Giorgio Chiellini 2021"), classIdB, defender, 86, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Paulo Dybala 2021"), classIdB, midfielder, 87, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Marco Verratti 2021"), classIdB, midfielder, 87, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Thomas Müller 2021"), classIdB, midfielder, 87, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Luka Modrić 2021"), classIdB, midfielder, 87, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Rodri 2021"), classIdB, midfielder, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Marcos Llorente 2021"), classIdB, midfielder, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Gerard Moreno 2021"), classIdB, midfielder, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Riyad Mahrez 2021"), classIdB, midfielder, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Parejo 2021"), classIdB, midfielder, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Sergio Busquets 2021"), classIdB, midfielder, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Thiago 2021"), classIdB, midfielder, 86, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Sadio Mané 2021"), classIdB, attacker, 89, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Erling Haaland 2021"), classIdB, attacker, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Raheem Sterling 2021"), classIdB, attacker, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Romelu Lukaku 2021"), classIdB, attacker, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Luis Suárez 2021"), classIdB, attacker, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jadon Sancho 2021"), classIdB, attacker, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Paulo Dybala 2021"), classIdB, attacker, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Ciro Immobile 2021"), classIdB, attacker, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Ángel Di María 2021"), classIdB, attacker, 88, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Sergio Agüero 2021"), classIdB, attacker, 88, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Wojciech Szczęsny 2021"), classIdC, goalkeeper, 87, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Hugo Lloris 2021"), classIdC, goalkeeper, 87, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Koen Casteels 2021"), classIdC, goalkeeper, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("De Gea 2021"), classIdC, goalkeeper, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Péter Gulácsi 2021"), classIdC, goalkeeper, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Doukara Sommer 2021"), classIdC, goalkeeper, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Kasper Schmeichel 2021"), classIdC, goalkeeper, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Samir Handanovič 2021"), classIdC, goalkeeper, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Mike Maignan 2021"), classIdC, goalkeeper, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Emiliano Martínez 2021"), classIdC, goalkeeper, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Édouard Mendy 2021"), classIdC, goalkeeper, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jordan Pickford 2021"), classIdC, goalkeeper, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Nick Pope 2021"), classIdC, goalkeeper, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Bernd Leno 2021"), classIdC, goalkeeper, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Lukáš Hrádecký 2021"), classIdC, goalkeeper, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Sergio Asenjo 2021"), classIdC, goalkeeper, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Dominik Livaković 2021"), classIdC, goalkeeper, 82, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Unai Simón 2021"), classIdC, goalkeeper, 82, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Raphaelinho Anjos 2021"), classIdC, goalkeeper, 82, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Pierluigi Gollini 2021"), classIdC, goalkeeper, 82, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Romulo Bounou 2021"), classIdC, goalkeeper, 82, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Anthony Lopes 2021"), classIdC, goalkeeper, 82, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Neto 2021"), classIdC, goalkeeper, 82, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Oliver Baumann 2021"), classIdC, goalkeeper, 82, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Matthijs de Ligt 2021"), classIdC, defender, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Carvajal 2021"), classIdC, defender, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Stefan de Vrij 2021"), classIdC, defender, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Kyle Walker 2021"), classIdC, defender, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Leonardo Bonucci 2021"), classIdC, defender, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Thiago Silva 2021"), classIdC, defender, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Theo Hernández 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Marcos Acuña 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("José María Giménez 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Ricardo Pereira 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Raphaël Guerreiro 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Felipe 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Matthias Ginter 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Stefan Savić 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Harry Maguire 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Lucas Digne 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Kieran Trippier 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Simon Kjær 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Piqué 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jesús Navas 2021"), classIdC, defender, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jules Koundé 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Alphonso Davies 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Aaron Wan-Bissaka 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Presnel Kimpembe 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Robin Gosens 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Lucas Hernández 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Angeliño 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Niklas Süle 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Gayà 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Antonio Rüdiger 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("John Stones 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Leonardo Spinazzola 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Francesco Acerbi 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Sebastián Coates 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Joel Matip 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Juan Cuadrado 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Kostas Manolas 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Alex Sandro 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Azpilicueta 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Toby Alderweireld 2021"), classIdC, defender, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jérôme Boateng 2021"), classIdC, defender, 83, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Marcus Rashford 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Wilfred Ndidi 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Sergej Milinković-Savić 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Kingsley Coman 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jorginho 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Koke 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Marco Reus 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("İlkay Gündoğan 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("David Silva 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Alejandro Gómez 2021"), classIdC, midfielder, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Phil Foden 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Kai Havertz 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Franck Yannick Kessié 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Nicolò Barella 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Leroy Sané 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Nabil Fekir 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("B. García Tielemans 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Marcelo Brozović 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Ricardo Pereira 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Raphaël Guerreiro 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Filip Kostić 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("D. Rolan Carrasco 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Marcel Sabitzer 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Luis Alberto 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Fernando 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jordan Henderson 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Georginio Wijnaldum 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jesús Navas 2021"), classIdC, midfielder, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Federico Valverde 2021"), classIdC, midfielder, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Mason Mount 2021"), classIdC, midfielder, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Arthur 2021"), classIdC, midfielder, 83, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jamie Vardy 2021"), classIdC, attacker, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Gerard Moreno 2021"), classIdC, attacker, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Riyad Mahrez 2021"), classIdC, attacker, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Lorenzo Insigne 2021"), classIdC, attacker, 86, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Lautaro Martínez 2021"), classIdC, attacker, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Oyarzabal 2021"), classIdC, attacker, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Memphis Depay 2021"), classIdC, attacker, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Roberto Firmino 2021"), classIdC, attacker, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Antoine Griezmann 2021"), classIdC, attacker, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Pierre-Emerick Aubameyang 2021"), classIdC, attacker, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Eden Hazard 2021"), classIdC, attacker, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Edinson Cavani 2021"), classIdC, attacker, 85, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Federico Chiesa 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("André Silva 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Timo Werner 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Hakim Strompf 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Jack Grealish 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Josip Iličić 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Wissam Ben Yedder 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Dušan Tadić 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Iago Aspas 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Edin Džeko 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Dries Mertens 2021"), classIdC, attacker, 84, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Ousmane Dembélé 2021"), classIdC, attacker, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Gabriel Jesus 2021"), classIdC, attacker, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Wout Weghorst 2021"), classIdC, attacker, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Marco Asensio 2021"), classIdC, attacker, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Andrej Kramarić 2021"), classIdC, attacker, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Duván Gürbüz 2021"), classIdC, attacker, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Ángel Correa 2021"), classIdC, attacker, 83, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Lucas Ocampos 2021"), classIdC, attacker, 83, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper0 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper1 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper2 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper3 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper4 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper5 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper6 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper7 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper8 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper9 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper10 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper11 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper12 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper13 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper14 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper15 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper16 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper17 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper18 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper19 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper20 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper21 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper22 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper23 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper24 2021"), classIdD, goalkeeper, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D goalkeeper25 2021"), classIdD, goalkeeper, 80, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper0 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper1 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper2 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper3 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper4 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper5 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper6 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper7 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper8 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper9 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper10 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper11 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper12 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper13 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper14 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper15 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper16 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper17 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper18 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper19 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper20 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper21 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper22 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper23 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper24 2021"), classIdE, goalkeeper, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E goalkeeper25 2021"), classIdE, goalkeeper, 75, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper0 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper1 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper2 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper3 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper4 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper5 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper6 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper7 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper8 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper9 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper10 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper11 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper12 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper13 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper14 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper15 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper16 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper17 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper18 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper19 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper20 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper21 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper22 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper23 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper24 2021"), classIdF, goalkeeper, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F goalkeeper25 2021"), classIdF, goalkeeper, 70, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper0 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper1 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper2 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper3 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper4 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper5 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper6 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper7 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper8 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper9 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper10 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper11 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper12 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper13 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper14 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper15 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper16 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper17 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper18 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper19 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper20 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper21 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper22 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper23 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper24 2021"), classIdG, goalkeeper, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G goalkeeper25 2021"), classIdG, goalkeeper, 65, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender0 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender1 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender2 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender3 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender4 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender5 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender5 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender6 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender7 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender8 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender9 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender10 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender11 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender12 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender13 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender14 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender15 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender16 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender17 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender18 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender19 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender20 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender21 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender22 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender23 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender24 2021"), classIdD, defender, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D defender25 2021"), classIdD, defender, 80, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender0 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender1 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender2 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender3 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender4 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender5 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender6 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender7 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender8 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender9 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender10 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender11 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender12 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender13 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender14 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender15 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender16 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender17 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender18 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender19 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender20 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender21 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender22 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender23 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender24 2021"), classIdE, defender, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E defender25 2021"), classIdE, defender, 75, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender0  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender1  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender2  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender3  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender4  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender5  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender6  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender7  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender8  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender9  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender10  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender11  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender12  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender13  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender14  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender15  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender16  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender17  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender18  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender19  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender20  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender21  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender22  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender23  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender24  2021"), classIdF, defender, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F defender25  2021"), classIdF, defender, 70, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender0 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender1 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender2 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender3 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender4 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender5 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender6 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender7 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender8 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender9 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender10 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender11 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender12 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender13 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender14 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender15 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender16 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender17 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender18 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender19 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender20 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender21 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender22 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender23 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender24 2021"), classIdG, defender, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G defender25 2021"), classIdG, defender, 65, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder0 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder1 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder2 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder3 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder4 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder5 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder6 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder7 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder8 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder9 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder10 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder11 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder12 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder13 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder14 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder15 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder16 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder17 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder18 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder19 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder20 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder21 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder22 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder23 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder24 2021"), classIdD, midfielder, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D midfielder25 2021"), classIdD, midfielder, 80, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder0 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder1 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder2 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder3 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder4 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder5 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder6 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder7 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder8 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder9 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder10 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder11 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder12 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder13 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder14 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder15 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder16 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder17 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder18 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder19 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder20 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder21 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder22 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder23 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder24 2021"), classIdE, midfielder, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E midfielder25 2021"), classIdE, midfielder, 75, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder0 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder1 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder2 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder3 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder4 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder5 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder6 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder7 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder8 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder9 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder10 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder11 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder12 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder13 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder14 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder15 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder16 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder17 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder18 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder19 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder20 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder21 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder22 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder23 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder24 2021"), classIdF, midfielder, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F midfielder25 2021"), classIdF, midfielder, 70, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder0 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder1 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder2 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder3 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder4 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder5 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder6 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder7 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder8 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder9 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder10 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder11 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder12 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder13 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder14 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder15 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder16 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder17 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder18 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder19 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder20 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder21 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder22 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder23 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder24 2021"), classIdG, midfielder, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G midfielder25 2021"), classIdG, midfielder, 65, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker0 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker1 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker2 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker3 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker4 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker5 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker6 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker7 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker8 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker9 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker10 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker11 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker12 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker13 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker14 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker15 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker16 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker17 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker18 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker19 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker20 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker21 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker22 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker23 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker24 2021"), classIdD, attacker, 80, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test D attacker25 2021"), classIdD, attacker, 80, 0);
    //
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker0 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker1 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker2 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker3 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker4 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker5 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker6 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker7 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker8 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker9 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker10 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker11 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker12 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker13 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker14 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker15 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker16 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker17 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker18 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker19 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker20 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker21 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker22 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker23 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker24 2021"), classIdE, attacker, 75, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test E attacker25 2021"), classIdE, attacker, 75, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker0 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker1 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker2 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker3 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker4 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker5 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker6 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker7 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker8 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker9 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker10 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker11 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker12 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker13 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker14 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker15 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker16 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker17 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker18 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker19 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker20 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker21 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker22 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker23 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker24 2021"), classIdF, attacker, 70, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test F attacker25 2021"), classIdF, attacker, 70, 0);

    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker0 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker1 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker2 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker3 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker4 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker5 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker6 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker7 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker8 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker9 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker10 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker11 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker12 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker13 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker14 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker15 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker16 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker17 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker18 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker19 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker20 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker21 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker22 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker23 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker24 2021"), classIdG, attacker, 65, 0);
    await controller.addPlayerCategory(curCategoryId++, await getByte32("Test G attacker25 2021"), classIdG, attacker, 65, 0);

};
